version: '2.3'
volumes: # Mount a data folder in the host to the container
  resin-data:
services:
  frontend:
    build: ./frontend
    network_mode: host
  backend:
    build: ./backend
    privileged: true
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
    ports:
      - "5050:5050"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes: # Mount a data folder in the host to the container
      - 'resin-data:/data'