version: '2.3'
volumes: # Mount a data folder in the host to the container
  resin-data:
services:
#  frontend:
#    build: ./frontend
#    network_mode: host
  backend:
    restart: always
    build: ./backend
    network_mode: host
    privileged: true
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    ports:
      - "5050:5050"
      - "80:80"
      - "443:443"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes: # Mount a data folder in the host to the container
      - 'resin-data:/data'