version: '2.1'
volumes: # Mount a data folder in the host to the container
  resin-data:
services:
  frontend:
    build: ./frontend
    network_mode: host
  backend:
    build: ./backend
    privileged: true
    ports:
      - "5050:5050"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes: # Mount a data folder in the host to the container
      - 'resin-data:/data'