version: '2.1'
services:
  frontend:
    build: ./frontend
    network_mode: host
  backend:
    build: ./backend
    privileged: true
    ports:
      - "5050:5050"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"